# Generated by Django 3.1.7 on 2021-04-10 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Your Full Name', max_length=40, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='donor_pic')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Please Enter Your Valid Phone Number.', max_length=128, region=None)),
                ('blood_group', models.CharField(choices=[('A', 'A+'), ('B', 'B+'), ('O', 'O+'), ('A', 'A-'), ('B', 'B-'), ('O', 'O-')], max_length=10, null=True)),
                ('current_address', models.CharField(max_length=50, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('updated', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
