# Generated by Django 3.1.7 on 2021-04-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatory', '0002_auto_20210410_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinformation',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donorinformation',
            name='current_address',
            field=models.CharField(help_text='Your devision and your city', max_length=50, null=True),
        ),
    ]
